logging:
  level:
    com.hdbsoft.spring: debug
  #pattern:
  #  console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  #  file: "%d %p %c{1.} [%t] %m%n"

  file: ./log/scheduling-tasks.log

