#log setting
logging:
  level:
    com.hdbsoft.spring: debug
  file: ./log/netty.log

#netty setting
boss.thread.count: 1
worker.thread.count: 1
so.keepalive: true
so.backlog: 100

#echo
echo:
  host: 127.0.0.1
  port: 13001

#hexproxy
hexproxy:
  host: 127.0.0.1
  port: 13002

#proxy
proxy:
  host: 127.0.0.1
  port: 13003

#telnet
telnet:
  host: 127.0.0.1
  port: 13004
  #is ssl support
  ssl: false



